import { H3_7_LOCK_KEY, type buildH37Release } from "./hyrox-h3-7-import-candidate";

type Candidate = ReturnType<typeof buildH37Release>["candidate"];
function sql(value: unknown) {
  if (value === null || value === undefined) return "null";
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number") return String(value);
  const text = typeof value === "string" ? value : JSON.stringify(value);
  return `'${text.replaceAll("'", "''")}'`;
}
function values(rows: unknown[][]) { return rows.map((row) => `  (${row.map(sql).join(", ")})`).join(",\n"); }

export function renderH37Rehearsal(candidate: Candidate) {
  const sourceRows = candidate.sources.map((row) => [row.sourceRef,row.locationId,row.url,row.canonicalUrl,row.sourceKind,row.publisherAuthority,row.availabilityState,row.lastCheckedAt,row.reviewRequired,row.contentHash,row.metadata]);
  const equipmentRows = candidate.equipment.map((row) => [row.equipmentRef,row.locationId,row.equipmentSlug,row.availabilityState,row.quantity,row.accessMode,row.reservationRequirement,row.verificationStatus,row.lastConfirmedAt,row.staleAt]);
  const capabilityRows = candidate.capabilities.map((row) => [row.capabilityRef,row.locationId,row.disciplineSlug,row.capabilitySlug,row.availabilityState,row.accessMode,row.reservationRequirement,row.verificationStatus,row.lastConfirmedAt,row.staleAt]);
  const evidenceRows = candidate.evidence.map((row) => [row.evidenceRef,row.sourceRef,row.targetType,row.targetRef,row.assertion,row.reviewStatus,row.evidenceText,row.structuredEvidence,row.observedAt,row.reviewedAt,row.contentHash]);
  const publicationRows = candidate.publicationPreview.locations.map((row) => [row.locationId, `{${row.equipmentSlugs.join(",")}}`, `{${row.capabilitySlugs.join(",")}}`, row.openTrainingAvailable]);
  return [
    "\\set ON_ERROR_STOP on",
    "-- LOCAL-ONLY, rollback-only H3-7 production-like rehearsal.",
    "do $$ begin if current_database() !~ '^gymmap_h3_7_rehearsal' then raise exception 'H3-7 rehearsal is local-only'; end if; end $$;",
    "begin;",
    `select pg_advisory_xact_lock(hashtextextended(${sql(H3_7_LOCK_KEY)},0));`,
    "create temp table h37_before as select (select count(*) from training_sources)::int sources,(select count(*) from location_equipment)::int equipment,(select count(*) from location_training_capabilities)::int capabilities,(select count(*) from training_evidence)::int evidence;",
    "create temp table h37_source_input(source_ref text primary key,location_id uuid,url text,canonical_url text,source_kind text,publisher_authority text,availability_state text,last_checked_at timestamptz,review_required boolean,content_hash text,metadata_json jsonb);",
    `insert into h37_source_input values\n${values(sourceRows)};`,
    "create temp table h37_equipment_input(equipment_ref text primary key,location_id uuid,equipment_slug text,availability_state text,quantity int,access_mode text,reservation_requirement text,verification_status text,last_confirmed_at timestamptz,stale_at timestamptz);",
    `insert into h37_equipment_input values\n${values(equipmentRows)};`,
    "create temp table h37_capability_input(capability_ref text primary key,location_id uuid,discipline_slug text,capability_slug text,availability_state text,access_mode text,reservation_requirement text,verification_status text,last_confirmed_at timestamptz,stale_at timestamptz);",
    `insert into h37_capability_input values\n${values(capabilityRows)};`,
    "create temp table h37_evidence_input(evidence_ref text primary key,source_ref text,target_type text,target_ref text,assertion text,review_status text,evidence_text text,structured_evidence jsonb,observed_at timestamptz,reviewed_at timestamptz,content_hash text);",
    `insert into h37_evidence_input values\n${values(evidenceRows)};`,
    "create temp table h37_publication_expected(location_id uuid primary key,equipment_slugs text[],capability_slugs text[],open_training boolean);",
    `insert into h37_publication_expected values\n${values(publicationRows)};`,
    "create temp table h37_source_map(source_ref text primary key,id uuid not null); create temp table h37_equipment_map(target_ref text primary key,id uuid not null); create temp table h37_capability_map(target_ref text primary key,id uuid not null);",
    `create or replace procedure pg_temp.apply_h37() language plpgsql as $$ begin
      if exists(select 1 from h37_source_input i left join gym_locations l on l.id=i.location_id where l.id is null or not l.is_active) then raise exception 'source target missing/inactive'; end if;
      if exists(select 1 from h37_source_input i join training_sources s on s.location_id=i.location_id and s.canonical_url=i.canonical_url where s.source_kind<>i.source_kind or s.publisher_authority<>i.publisher_authority) then raise exception 'source authority mismatch'; end if;
      if exists(select 1 from h37_source_input i join training_sources s on s.location_id=i.location_id and s.canonical_url=i.canonical_url and s.source_kind=i.source_kind and s.publisher_authority=i.publisher_authority where s.url<>i.url or s.availability_state<>i.availability_state or s.review_required<>i.review_required or s.content_hash<>i.content_hash or s.last_checked_at<>i.last_checked_at) then raise exception 'source semantic conflict'; end if;
      insert into training_sources(location_id,url,canonical_url,source_kind,publisher_authority,availability_state,last_checked_at,review_required,content_hash,metadata_json)
      select i.location_id,i.url,i.canonical_url,i.source_kind,i.publisher_authority,i.availability_state,i.last_checked_at,i.review_required,i.content_hash,i.metadata_json from h37_source_input i where not exists(select 1 from training_sources s where s.location_id=i.location_id and s.canonical_url=i.canonical_url and s.source_kind=i.source_kind and s.publisher_authority=i.publisher_authority);
      truncate h37_source_map; insert into h37_source_map select i.source_ref,(array_agg(s.id))[1] from h37_source_input i join training_sources s on s.location_id=i.location_id and s.canonical_url=i.canonical_url and s.source_kind=i.source_kind and s.publisher_authority=i.publisher_authority group by i.source_ref having count(*)=1;
      if (select count(*) from h37_source_map)<>16 or (select count(distinct id) from h37_source_map)<>16 then raise exception 'source map incomplete/colliding'; end if;
      if exists(select 1 from h37_equipment_input i join equipment_types t on t.slug=i.equipment_slug join location_equipment e on e.location_id=i.location_id and e.equipment_type_id=t.id where row(e.availability_state,e.quantity,e.access_mode,e.reservation_requirement,e.verification_status,e.last_confirmed_at,e.stale_at) is distinct from row(i.availability_state,i.quantity,i.access_mode,i.reservation_requirement,i.verification_status,i.last_confirmed_at,i.stale_at)) then raise exception 'equipment semantic conflict/freshness regression'; end if;
      insert into location_equipment(location_id,equipment_type_id,availability_state,quantity,access_mode,reservation_requirement,verification_status,last_confirmed_at,stale_at) select i.location_id,t.id,i.availability_state,i.quantity,i.access_mode,i.reservation_requirement,i.verification_status,i.last_confirmed_at,i.stale_at from h37_equipment_input i join equipment_types t on t.slug=i.equipment_slug on conflict(location_id,equipment_type_id) do nothing;
      truncate h37_equipment_map; insert into h37_equipment_map select i.equipment_ref,e.id from h37_equipment_input i join equipment_types t on t.slug=i.equipment_slug join location_equipment e on e.location_id=i.location_id and e.equipment_type_id=t.id and row(e.availability_state,e.quantity,e.access_mode,e.reservation_requirement,e.verification_status,e.last_confirmed_at,e.stale_at) is not distinct from row(i.availability_state,i.quantity,i.access_mode,i.reservation_requirement,i.verification_status,i.last_confirmed_at,i.stale_at);
      if (select count(*) from h37_equipment_map)<>73 then raise exception 'equipment map incomplete'; end if;
      if exists(select 1 from h37_capability_input i join training_disciplines d on d.slug=i.discipline_slug join location_training_disciplines ld on ld.location_id=i.location_id and ld.discipline_id=d.id join training_capability_types t on t.slug=i.capability_slug join location_training_capabilities c on c.location_training_discipline_id=ld.id and c.capability_type_id=t.id where row(c.availability_state,c.access_mode,c.reservation_requirement,c.verification_status,c.last_confirmed_at,c.stale_at) is distinct from row(i.availability_state,i.access_mode,i.reservation_requirement,i.verification_status,i.last_confirmed_at,i.stale_at)) then raise exception 'capability semantic conflict/freshness regression'; end if;
      insert into location_training_capabilities(location_training_discipline_id,capability_type_id,availability_state,access_mode,reservation_requirement,verification_status,last_confirmed_at,stale_at) select ld.id,t.id,i.availability_state,i.access_mode,i.reservation_requirement,i.verification_status,i.last_confirmed_at,i.stale_at from h37_capability_input i join training_disciplines d on d.slug=i.discipline_slug join location_training_disciplines ld on ld.location_id=i.location_id and ld.discipline_id=d.id join training_capability_types t on t.slug=i.capability_slug on conflict(location_training_discipline_id,capability_type_id) do nothing;
      truncate h37_capability_map; insert into h37_capability_map select i.capability_ref,c.id from h37_capability_input i join training_disciplines d on d.slug=i.discipline_slug join location_training_disciplines ld on ld.location_id=i.location_id and ld.discipline_id=d.id join training_capability_types t on t.slug=i.capability_slug join location_training_capabilities c on c.location_training_discipline_id=ld.id and c.capability_type_id=t.id and row(c.availability_state,c.access_mode,c.reservation_requirement,c.verification_status,c.last_confirmed_at,c.stale_at) is not distinct from row(i.availability_state,i.access_mode,i.reservation_requirement,i.verification_status,i.last_confirmed_at,i.stale_at);
      if (select count(*) from h37_capability_map)<>25 then raise exception 'capability map incomplete'; end if;
      if exists(select 1 from h37_evidence_input i join training_evidence e on e.content_hash=i.content_hash join h37_source_map sm on sm.source_ref=i.source_ref where e.training_source_id<>sm.id or e.assertion<>i.assertion or e.review_status<>i.review_status or (i.target_type='location_equipment' and e.location_equipment_id is distinct from (select id from h37_equipment_map where target_ref=i.target_ref)) or (i.target_type='location_training_capability' and e.location_training_capability_id is distinct from (select id from h37_capability_map where target_ref=i.target_ref))) then raise exception 'evidence hash/target collision'; end if;
      insert into training_evidence(training_source_id,location_training_capability_id,location_equipment_id,assertion,review_status,evidence_text,structured_evidence,observed_at,reviewed_at,content_hash) select sm.id,case when i.target_type='location_training_capability' then cm.id end,case when i.target_type='location_equipment' then em.id end,i.assertion,i.review_status,i.evidence_text,i.structured_evidence,i.observed_at,i.reviewed_at,i.content_hash from h37_evidence_input i join h37_source_map sm using(source_ref) left join h37_capability_map cm on cm.target_ref=i.target_ref left join h37_equipment_map em on em.target_ref=i.target_ref where (cm.id is not null)<>(em.id is not null) and not exists(select 1 from training_evidence e where e.content_hash=i.content_hash);
      if exists(select 1 from h37_evidence_input i left join training_evidence e on e.content_hash=i.content_hash where e.id is null) then raise exception 'evidence map incomplete'; end if;
    end $$;`,
    "call pg_temp.apply_h37();",
    `do $$ declare b h37_before%rowtype; n bigint; begin select * into b from h37_before;
      if (select count(*) from training_sources)<>b.sources+16 or (select count(*) from location_equipment)<>b.equipment+73 or (select count(*) from location_training_capabilities)<>b.capabilities+25 or (select count(*) from training_evidence)<>b.evidence+98 then raise exception 'first-pass delta mismatch'; end if;
      if (select count(*) from published_location_equipment)<>109 or (select count(distinct location_id) from published_location_equipment)<>22 then raise exception 'equipment publication mismatch'; end if;
      if (select count(*) from published_location_training_capabilities)<>41 or (select count(distinct location_id) from published_location_training_capabilities)<>21 then raise exception 'capability publication mismatch'; end if;
      if (select count(*) from published_location_training_capabilities where capability_slug='open-training')<>5 or (select count(*) from published_location_training_capabilities where capability_slug='competition-simulation')<>13 then raise exception 'capability projection mismatch'; end if;
      if (select count(*) from (select location_id from published_location_equipment union select location_id from published_location_training_capabilities) u)<>25 then raise exception 'enriched union mismatch'; end if;
      if (select count(*) from published_location_training_disciplines where discipline_slug='hyrox')<>82 or (select official_location_count from published_training_discipline_summary where slug='hyrox')<>82 then raise exception 'HYROX publication changed'; end if;
      select max(total_count) into n from search_training_locations('hyrox',p_limit=>100); if n<>82 then raise exception 'search total changed'; end if;
      if exists(select 1 from h37_publication_expected x join lateral (select * from search_training_locations('hyrox',p_limit=>100) s where s.location_id=x.location_id) s on true where s.equipment_slugs<>x.equipment_slugs or s.capability_slugs<>x.capability_slugs or s.open_training_available<>x.open_training) then raise exception 'search projection mismatch'; end if;
    end $$;`,
    "create temp table h37_after_first as select (select count(*) from training_sources)::int sources,(select count(*) from location_equipment)::int equipment,(select count(*) from location_training_capabilities)::int capabilities,(select count(*) from training_evidence)::int evidence,(select min(last_confirmed_at) from h37_equipment_input)::timestamptz equipment_confirmed,(select min(last_confirmed_at) from h37_capability_input)::timestamptz capability_confirmed;",
    "call pg_temp.apply_h37();",
    "do $$ declare a h37_after_first%rowtype; begin select * into a from h37_after_first; if row((select count(*) from training_sources),(select count(*) from location_equipment),(select count(*) from location_training_capabilities),(select count(*) from training_evidence),(select min(last_confirmed_at) from h37_equipment_input),(select min(last_confirmed_at) from h37_capability_input))<>row(a.sources,a.equipment,a.capabilities,a.evidence,a.equipment_confirmed,a.capability_confirmed) then raise exception 'second pass not idempotent'; end if; end $$;",
    "do $$ begin begin update h37_source_input set availability_state='unknown' where source_ref=(select min(source_ref) from h37_source_input); call pg_temp.apply_h37(); raise exception 'source conflict did not fail'; exception when others then if sqlerrm='source conflict did not fail' then raise; end if; end; end $$;",
    "do $$ begin begin update h37_source_input set publisher_authority='discovery' where source_ref=(select min(source_ref) from h37_source_input); call pg_temp.apply_h37(); raise exception 'source authority conflict did not fail'; exception when others then if sqlerrm='source authority conflict did not fail' then raise; end if; end; end $$;",
    "do $$ begin begin update h37_equipment_input set availability_state='unknown' where equipment_ref=(select min(equipment_ref) from h37_equipment_input); call pg_temp.apply_h37(); raise exception 'equipment conflict did not fail'; exception when others then if sqlerrm='equipment conflict did not fail' then raise; end if; end; end $$;",
    "do $$ begin begin update h37_capability_input set availability_state='unknown' where capability_ref=(select min(capability_ref) from h37_capability_input); call pg_temp.apply_h37(); raise exception 'capability conflict did not fail'; exception when others then if sqlerrm='capability conflict did not fail' then raise; end if; end; end $$;",
    "do $$ begin begin update h37_evidence_input set target_ref=(select target_ref from h37_evidence_input where evidence_ref<>(select min(evidence_ref) from h37_evidence_input) limit 1) where evidence_ref=(select min(evidence_ref) from h37_evidence_input); call pg_temp.apply_h37(); raise exception 'evidence conflict did not fail'; exception when others then if sqlerrm='evidence conflict did not fail' then raise; end if; end; end $$;",
    "do $$ begin begin update h37_equipment_input set last_confirmed_at=last_confirmed_at-interval '1 day',stale_at=stale_at-interval '1 day' where equipment_ref=(select min(equipment_ref) from h37_equipment_input); call pg_temp.apply_h37(); raise exception 'freshness regression did not fail'; exception when others then if sqlerrm='freshness regression did not fail' then raise; end if; end; end $$;",
    "rollback;",
    "do $$ declare n bigint; begin if (select count(*) from training_sources)<>92 or (select count(*) from location_equipment)<>36 or (select count(*) from location_training_capabilities)<>16 or (select count(*) from training_evidence)<>216 then raise exception 'rollback baseline mismatch'; end if; if (select count(*) from published_location_equipment)<>36 or (select count(*) from published_location_training_capabilities)<>16 then raise exception 'rollback publication mismatch'; end if; select max(total_count) into n from search_training_locations('hyrox',p_limit=>100); if n<>82 then raise exception 'rollback search mismatch'; end if; end $$;",
    "select 'H3-7 atomic/publication/search/idempotency/conflict/rollback rehearsal PASS' as result;",
    "",
  ].join("\n");
}
