import type {
  AdminDataset,
  ClassSchedule,
  GymBrand,
  GymLocation,
  IngestionItem,
  IngestionRun,
  Program,
  ProgramAlias,
  SearchResult,
  SourcePage,
} from "@/lib/types";

const now = new Date("2026-04-13T09:00:00+09:00").toISOString();

export const sampleBrands: GymBrand[] = [
  {
    id: "brand-golds",
    name: "Gold's Gym",
    slug: "golds-gym",
    official_url: "https://www.goldsgym.jp/",
    description: "フリーウェイトとスタジオプログラムの両方が強いブランド",
    created_at: now,
    updated_at: now,
  },
  {
    id: "brand-konami",
    name: "Konami Sports Club",
    slug: "konami-sports-club",
    official_url: "https://www.konami.com/sportsclub/",
    description: "幅広い会員層向けの総合型スポーツクラブ",
    created_at: now,
    updated_at: now,
  },
  {
    id: "brand-central",
    name: "Central Sports",
    slug: "central-sports",
    official_url: "https://www.central.co.jp/",
    description: "スイミングとスタジオのバランスが良い総合型ジム",
    created_at: now,
    updated_at: now,
  },
];

export const sampleLocations: GymLocation[] = [
  {
    id: "loc-golds-shibuya",
    brand_id: "brand-golds",
    name: "Gold's Gym 渋谷東京店",
    slug: "golds-gym-shibuya",
    postal_code: "150-0042",
    prefecture: "東京都",
    city: "渋谷区",
    address_line: "宇田川町 31-2 渋谷BEAM 6F",
    latitude: 35.6618,
    longitude: 139.6981,
    nearest_station: "渋谷駅",
    official_url: "https://www.goldsgym.jp/shop/13110",
    source_url: "https://www.goldsgym.jp/shop/13110/program",
    is_active: true,
    last_verified_at: now,
    created_at: now,
    updated_at: now,
  },
  {
    id: "loc-golds-ginza",
    brand_id: "brand-golds",
    name: "Gold's Gym 銀座中央店",
    slug: "golds-gym-ginza",
    postal_code: "104-0061",
    prefecture: "東京都",
    city: "中央区",
    address_line: "銀座 1-2-4 サクセス銀座ファーストビル",
    latitude: 35.6745,
    longitude: 139.769,
    nearest_station: "銀座一丁目駅",
    official_url: "https://www.goldsgym.jp/shop/13120",
    source_url: "https://www.goldsgym.jp/shop/13120/program",
    is_active: true,
    last_verified_at: now,
    created_at: now,
    updated_at: now,
  },
  {
    id: "loc-konami-shinjuku",
    brand_id: "brand-konami",
    name: "コナミスポーツクラブ 新宿",
    slug: "konami-shinjuku",
    postal_code: "160-0023",
    prefecture: "東京都",
    city: "新宿区",
    address_line: "西新宿 1-1-5",
    latitude: 35.6905,
    longitude: 139.6994,
    nearest_station: "新宿駅",
    official_url: "https://www.konami.com/sportsclub/shisetsu/shinjuku/",
    source_url: "https://www.konami.com/sportsclub/shisetsu/shinjuku/program/",
    is_active: true,
    last_verified_at: now,
    created_at: now,
    updated_at: now,
  },
  {
    id: "loc-konami-ikebukuro",
    brand_id: "brand-konami",
    name: "コナミスポーツクラブ 池袋",
    slug: "konami-ikebukuro",
    postal_code: "171-0022",
    prefecture: "東京都",
    city: "豊島区",
    address_line: "南池袋 1-28-1",
    latitude: 35.7289,
    longitude: 139.7101,
    nearest_station: "池袋駅",
    official_url: "https://www.konami.com/sportsclub/shisetsu/ikebukuro/",
    source_url: "https://www.konami.com/sportsclub/shisetsu/ikebukuro/program/",
    is_active: true,
    last_verified_at: now,
    created_at: now,
    updated_at: now,
  },
  {
    id: "loc-central-omori",
    brand_id: "brand-central",
    name: "セントラルスポーツ 大森",
    slug: "central-omori",
    postal_code: "143-0016",
    prefecture: "東京都",
    city: "大田区",
    address_line: "大森北 1-8-2 icot大森",
    latitude: 35.5889,
    longitude: 139.7284,
    nearest_station: "大森駅",
    official_url: "https://www.central.co.jp/club/omori/",
    source_url: "https://www.central.co.jp/club/omori/schedule/",
    is_active: true,
    last_verified_at: now,
    created_at: now,
    updated_at: now,
  },
  {
    id: "loc-central-kinshicho",
    brand_id: "brand-central",
    name: "セントラルスポーツ 錦糸町",
    slug: "central-kinshicho",
    postal_code: "130-0013",
    prefecture: "東京都",
    city: "墨田区",
    address_line: "錦糸 1-5-10",
    latitude: 35.6974,
    longitude: 139.8149,
    nearest_station: "錦糸町駅",
    official_url: "https://www.central.co.jp/club/kinshicho/",
    source_url: "https://www.central.co.jp/club/kinshicho/schedule/",
    is_active: true,
    last_verified_at: now,
    created_at: now,
    updated_at: now,
  },
];

export const samplePrograms: Program[] = [
  {
    id: "program-bodycombat",
    name: "BODYCOMBAT",
    slug: "bodycombat",
    category: "Les Mills",
    description: "格闘技の動きを取り入れた有酸素プログラム",
    intensity_level: 4,
    beginner_friendly: false,
    default_duration_minutes: 45,
    created_at: now,
    updated_at: now,
  },
  {
    id: "program-bodypump",
    name: "BODYPUMP",
    slug: "bodypump",
    category: "Les Mills",
    description: "バーベルを使った全身筋力トレーニング",
    intensity_level: 4,
    beginner_friendly: false,
    default_duration_minutes: 45,
    created_at: now,
    updated_at: now,
  },
  {
    id: "program-yoga",
    name: "ヨガ",
    slug: "yoga",
    category: "Mind & Body",
    description: "呼吸と姿勢を整える定番クラス",
    intensity_level: 2,
    beginner_friendly: true,
    default_duration_minutes: 60,
    created_at: now,
    updated_at: now,
  },
  {
    id: "program-pilates",
    name: "ピラティス",
    slug: "pilates",
    category: "Mind & Body",
    description: "体幹を意識したコンディショニング",
    intensity_level: 2,
    beginner_friendly: true,
    default_duration_minutes: 50,
    created_at: now,
    updated_at: now,
  },
];

export const sampleProgramAliases: ProgramAlias[] = [
  {
    id: "alias-1",
    program_id: "program-bodycombat",
    alias_name: "ボディコンバット",
    created_at: now,
  },
  {
    id: "alias-2",
    program_id: "program-bodypump",
    alias_name: "ボディパンプ",
    created_at: now,
  },
  {
    id: "alias-3",
    program_id: "program-yoga",
    alias_name: "ヨガ",
    created_at: now,
  },
  {
    id: "alias-4",
    program_id: "program-pilates",
    alias_name: "ピラティス",
    created_at: now,
  },
];

export const sampleSchedules: ClassSchedule[] = [
  {
    id: "schedule-1",
    location_id: "loc-golds-shibuya",
    program_id: "program-bodycombat",
    raw_program_name: "BODYCOMBAT 45",
    weekday: "monday",
    start_time: "19:00",
    end_time: "19:45",
    duration_minutes: 45,
    studio_name: "Studio A",
    instructor_name: "Saito",
    source_page_url: "https://example.com/golds-shibuya/bodycombat",
    source_snapshot_id: null,
    valid_from: "2026-04-01",
    valid_to: null,
    extracted_at: now,
    created_at: now,
    updated_at: now,
  },
  {
    id: "schedule-2",
    location_id: "loc-golds-ginza",
    program_id: "program-bodypump",
    raw_program_name: "BODYPUMP 45",
    weekday: "wednesday",
    start_time: "18:30",
    end_time: "19:15",
    duration_minutes: 45,
    studio_name: "メインスタジオ",
    instructor_name: "Tanaka",
    source_page_url: "https://example.com/golds-ginza/bodypump",
    source_snapshot_id: null,
    valid_from: "2026-04-01",
    valid_to: null,
    extracted_at: now,
    created_at: now,
    updated_at: now,
  },
  {
    id: "schedule-3",
    location_id: "loc-konami-shinjuku",
    program_id: "program-yoga",
    raw_program_name: "朝のヨガ",
    weekday: "tuesday",
    start_time: "10:00",
    end_time: "11:00",
    duration_minutes: 60,
    studio_name: "Studio 2",
    instructor_name: "Aki",
    source_page_url: "https://example.com/konami-shinjuku/yoga",
    source_snapshot_id: null,
    valid_from: "2026-04-01",
    valid_to: null,
    extracted_at: now,
    created_at: now,
    updated_at: now,
  },
  {
    id: "schedule-4",
    location_id: "loc-konami-ikebukuro",
    program_id: "program-pilates",
    raw_program_name: "ベーシックピラティス",
    weekday: "friday",
    start_time: "20:00",
    end_time: "20:50",
    duration_minutes: 50,
    studio_name: "ボディスタジオ",
    instructor_name: "Mori",
    source_page_url: "https://example.com/konami-ikebukuro/pilates",
    source_snapshot_id: null,
    valid_from: "2026-04-01",
    valid_to: null,
    extracted_at: now,
    created_at: now,
    updated_at: now,
  },
  {
    id: "schedule-5",
    location_id: "loc-central-omori",
    program_id: "program-yoga",
    raw_program_name: "リラックスヨガ",
    weekday: "saturday",
    start_time: "09:30",
    end_time: "10:30",
    duration_minutes: 60,
    studio_name: "スタジオ Green",
    instructor_name: "Kato",
    source_page_url: "https://example.com/central-omori/yoga",
    source_snapshot_id: null,
    valid_from: "2026-04-01",
    valid_to: null,
    extracted_at: now,
    created_at: now,
    updated_at: now,
  },
  {
    id: "schedule-6",
    location_id: "loc-central-kinshicho",
    program_id: "program-bodycombat",
    raw_program_name: "BODYCOMBAT 30",
    weekday: "sunday",
    start_time: "13:00",
    end_time: "13:30",
    duration_minutes: 30,
    studio_name: "スタジオ Red",
    instructor_name: "Nakamura",
    source_page_url: "https://example.com/central-kinshicho/bodycombat",
    source_snapshot_id: null,
    valid_from: "2026-04-01",
    valid_to: null,
    extracted_at: now,
    created_at: now,
    updated_at: now,
  },
];

export const sampleSourcePages: SourcePage[] = sampleLocations.map((location, index) => ({
  id: `source-${index + 1}`,
  location_id: location.id,
  source_type: "location_schedule",
  url: location.source_url ?? location.official_url ?? "",
  format: "html",
  parser_key: "manual_seed_v1",
  last_fetched_at: now,
  last_parsed_at: now,
  fetch_status: "success",
  parse_status: "success",
  notes: "MVP seed data",
  created_at: now,
  updated_at: now,
}));

export const sampleIngestionRuns: IngestionRun[] = [
  {
    id: "run-1",
    started_at: now,
    finished_at: now,
    trigger_type: "manual",
    status: "success",
    total_sources: sampleSourcePages.length,
    success_count: sampleSourcePages.length,
    failed_count: 0,
    warning_count: 0,
    logs_json: { message: "Seed data inserted" },
  },
];

export const sampleIngestionItems: IngestionItem[] = sampleSourcePages.map((page, index) => ({
  id: `item-${index + 1}`,
  run_id: "run-1",
  source_page_id: page.id,
  status: "success",
  detected_records: 1,
  inserted_records: 1,
  updated_records: 0,
  error_message: null,
  raw_output_json: { url: page.url, parser_key: page.parser_key },
  created_at: now,
}));

export function buildSampleSearchResults(): SearchResult[] {
  return sampleSchedules.map((schedule) => {
    const location = sampleLocations.find((item) => item.id === schedule.location_id);
    const brand = sampleBrands.find((item) => item.id === location?.brand_id);
    const program = samplePrograms.find((item) => item.id === schedule.program_id);

    if (!location || !brand || !program) {
      throw new Error("Sample data is inconsistent.");
    }

    return {
      schedule,
      location: { ...location, brand },
      brand,
      program,
    };
  });
}

export function buildAdminSampleDataset(): AdminDataset {
  return {
    gym_brands: sampleBrands,
    gym_locations: sampleLocations,
    programs: samplePrograms,
    class_schedules: sampleSchedules,
    source_pages: sampleSourcePages,
    ingestion_runs: sampleIngestionRuns,
    ingestion_items: sampleIngestionItems,
  };
}
