-- 初期のサンプル seed は削除済みです。
-- 実データは JEXER 抽出/import スクリプト、または必要な SQL を個別に投入してください。
--
-- 例:
-- 1. gym_brands / gym_locations を追加
-- 2. scripts/experimental/run-jexer-extraction.ts で抽出
-- 3. scripts/experimental/import-jexer-extraction.ts で class_schedules に投入
